---
title: "Homework on partial dimension"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: false
---

In this homework I ask you to create a function `g(n,d)` that returns a matrix of dimension (nx2) where each row in $[0,1]^2$ represents the coordinates of element in a set. This set, as n grows large needs to have dimension `d` where d is potentialy fractional in (1,2).

```{r}
# A simple set that generates curve of length L

g1d <- function(n,l=1) {
  X = seq(0,1,l=n)
  Y = (l*X) %% 1
  return(cbind(X,Y))
}

plot( g1d(100,3)    )

```

Next we want to be able evaluate the dimension of the set.

```{r}

# we cluster with different number of groups, we need to make sure that we have enough 
# points in our set

dd  = g1d(1e5,1)
rr = data.frame()
for (k in c(5:50)) {
  ks = kmeans(dd,centers = k,iter.max = 100,nstart = 10)
  rr = rbind(rr,data.frame(k=k,ss=sum(ks$withinss)))
}

ggplot(rr,aes(x=log(k),y=log(ss))) + geom_point() + geom_line()

fit = lm(log(ss) ~ log(k),rr)


```