
<br>

This website contains content for the graduate course Econ 34430 taught by [T. Lamadon](http://www.lamadon.com) in the Econ department at University of Chicago. 

<a class="btn btn-danger" href="https://chicago-econ-34430.slack.com/signup" role="button">Slack group</a>  <a class="btn btn-info" href="pdf/econ-34430-syllabus.pdf" role="button">Syllabus</a> 

## Course description

The class covers recent developments in the understanding of the determinants of employment and earnings in the labor market. We start by studying extensive and intensive labor supply decisions in the short and long run. We then look at the effect of uncertainty in earnings by studying the joint dynamics of earnings and consumption. We continue by studying contracting between firms and workers and look at the link between firm shocks and employee earnings. Finally, the course covers models with two-sided heterogeneity with complementarities, sorting and mobility frictions. The methods presented in the course range from nonparametric econometrics methods to solving equilibrium and dynamic contracting problems. Students should expect to learn how to work with data and how to develop, solve and evaluate structural models of the labor market.

## Getting in touch

If you are a student for the course, please sign on the [slack group](https://join.slack.com/t/chicago-econ-34430/signup).

## Homeworks

You can submit your homework either as solo or as a group of two. To submit your homework, create a channel in our slack group with a name starting with `grp_` and then with the initials of the members of your group. For instance Alex and Lucy would be `grp_al`. Then please add me as members of that group. You can make your group **private**.

Submit your homework in the `R markdown` format. It should be a runnable file that takes as input only a data file (if needed). Please submit the `Rmd` file and the generated output, either in `html` or in `pdf`. Rstudio is great to work on R-markdown files, I recommend it. See [here](http://rmarkdown.rstudio.com/) to get started. You can also download each homework original Markdown file to use as a starting point.

## Getting started with R {#start}

You will first need to install `R` and `Rstudio`. To do use the following links:

 - [R](https://cran.rstudio.com/) & [RStudio](https://www.rstudio.com/products/rstudio/download/)
 - `data.table` [tutorial](https://cran.r-project.org/web/packages/data.table/vignettes/datatable-intro.pdf) and [cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/img/blog/data+table+cheat+sheet.pdf).
 - `ggplot2` [tutorial](http://www.ceb-institute.org/bbs/wp-content/uploads/2011/09/handout_ggplot2.pdf), [cheatsheet](http://www.rstudio.com/wp-content/uploads/2015/12/ggplot2-cheatsheet-2.0.pdf) and [full documentation](http://docs.ggplot2.org/current/). An interactive online course at  [datacamp](https://www.datacamp.com/courses/data-visualization-with-ggplot2-1)


<!-- Place this tag in your head or just before your close body tag. -->
<script async defer src="https://buttons.github.io/buttons.js"></script>  
